export default  [
    {
        id: 1,
        firstName: 'Anton',
        lastName: 'Kudryavtsev',
        email: 'qpuolet@gmail.com',
        image: './img/anton.jpg',
        phoneNumber: '+375447369637',
    },
    {
        id: 2,
        firstName: 'Oleg',
        lastName: 'Lipskiy',
        email: 'onetwothree@gmail.com',
        image: './img/james.jpg',
        phoneNumber: '+375447369637',
    },
    {
        id: 3,
        firstName: 'James',
        lastName: 'McArthur',
        email: 'dasdsad@gmail.com',
        image: './img/paul.jpg',
        phoneNumber: '+375447369637',
    },
    {
        id: 4,
        firstName: 'Peter',
        lastName: 'Parker',
        email: 'parker@gmail.com',
        image: './img/andrew.jpg',
        phoneNumber: '+375447369637',
    },
    {
        id: 5,
        firstName: 'Sam',
        lastName: 'Smith',
        email: 'whereareyounowwhenineedu@gmail.com',
        image: './img/paul.jpg',
        phoneNumber: '+375447369637',
    },
    {
        id: 6,
        firstName: 'Maks',
        lastName: 'Somsonov',
        email: 'maks.samsonov@gmail.com',
        image: './img/james.jpg',
        phoneNumber: '+375447369637',
    },
    {
        id: 7,
        firstName: 'Antony',
        lastName: 'Checkhov',
        email: 'specabr@gmail.com',
        image: './img/anton.jpg',
        phoneNumber: '+375447369637',
    },
    {
        id: 8,
        firstName: 'Rodrigues',
        lastName: 'Panamers',
        email: 'panames@gmail.com',
        image: './img/andrew.jpg',
        phoneNumber: '+375447369637',
    }
]
